disabled_rules: # some rules are only opt-in
#- empty_count
#- missing_docs
#- trailing_newline
- trailing_whitespace
- vertical_whitespace
#- todo
#- cyclomatic_complexity
#- function_body_length
#- file_length
#- legacy_constant
- line_length
#- empty_parentheses_with_trailing_closure
#- variable_name
#- type_body_length

# Find all the available rules by running:
# swiftlint rules

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
